### ISSUE TITLE
Missing vocabulary file

### ISSUE THREAD

**Issue by MohitShridhar** [ybisk/GroundedLanguage#4]
The 'JSONReader/data/2016-NAACL/SRD/Vocabulary.txt' file seems to be missing (referenced in RNN-SRD.py). Is this supposed to be generated somewhere?

Regards

**Comment by ybisk** [comment]
Hi, yes, that file is generated inside the JSONReader CreateTrainingData file.

https://github.com/ybisk/GroundedLanguage/blob/0c6bcaacf08f1eddb4a9449521965b0b8623644d/JSONReader/src/main/java/CreateTrainingData.java#L112

That being said you can definitely do without it.  The NAACL results were originally achieved using the julia files.  You can also, train RNN-SRD.py and evaluate without it.  The training if-statement will also perform evaluation.  The section that requires the Vocabulary file is only used to run a server process which handles single action queries in natural language and therefore requires the word->int mapping.

Hope that helps
